kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: simple-dotnet6-startup
  labels:
    app: simple-dotnet6-startup
    app.kubernetes.io/component: simple-dotnet6-startup
    app.kubernetes.io/instance: simple-dotnet6-startup
    app.kubernetes.io/name: simple-dotnet6-startup
    app.kubernetes.io/part-of: simple-dotnet6-startup
    app.openshift.io/runtime-version: latest
spec:
  host: simple-dotnet6-startup-simple-dotnet6-app.apps-crc.testing
  to:
    kind: Service
    name: simple-dotnet6-startup
    weight: 100
  port:
    targetPort: 7111-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None